#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    if [[ -z $TMUX ]]; then
        selected=$(find ~/go/src/git.yabbi.me -mindepth 2 -maxdepth 2 -type d | fzf --height 40% --layout=reverse --header='')
    else
        selected=$(find ~/go/src/git.yabbi.me -mindepth 2 -maxdepth 2 -type d | fzf-tmux -p --border=rounded --color=border:#b7bdf8 --header='')
    fi
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name="$(basename $(dirname "$selected") | tr . _)/$(basename "$selected" | tr . _)"

if [[ -z $TMUX ]] then
    if tmux has-session -t "$selected_name" 2>/dev/null; then
        tmux attach-session -t $selected_name
        exit 0
    fi
    tmux new-session -s $selected_name -c $selected
    exit 0
fi

if ! tmux has-session -t "$selected_name" 2>/dev/null; then
    tmux new-session -ds $selected_name -c $selected
fi

tmux switch-client -t $selected_name
